### PR TITLE
Pending app

### PR DESCRIPTION
**Pull request by cdschmitz**
Need this app to exist before setting up the email invitation stuff.

### CODE REVIEW

**Comment by khaosans** [comment]
Are we committing RealEstate/db.sqlite3?  Since we're trying to move to postgres.

**Comment by cdschmitz** [comment]
I think we should keep the sqlite db for development.  The postgres server is just going to be used for production, otherwise it would be too chaotic having 7 people fiddling with the same db.  I just thought it would be helpful for us to set up the postgres stuff now so we are not scrambling at the end when trying to deploy.

**Comment by khaosans** [comment]
So I looked over it and I really couldn't find anything besides the comment I made earlier.  One thing I do notice is that we have no unit tests.  This is something I'll look into and hopefully can get going by end of the week.

**Comment by AaronHampshire** [comment]
I gave it a quick once-over. Looks good. Merging.

**Pull request merged**
