### PR TITLE
Add category from eval page

### PR DESCRIPTION
**Pull request by AaronHampshire**
This feature allows a homebuyer to add and weight a category from the home evaluation page. 

Some things to look for:

(1) The UI on the modal seems weird. Any suggestions?
(2) The way I implemented the Category Slider seemed a bit hacky. There may be a better way.

### CODE REVIEW

**Comment by cdschmitz** [comment]
Database was deleted

**Comment by AaronHampshire** [comment]
DB added back in. Sorry about that.

**Comment by cdschmitz** [comment]
:+1:

**Comment by sanjuktasen** [comment]
1. After adding the category user should be able to delete and edit the added category delete option just like they can do on  home name. 
2. when I want to add summary name at first it breaks and says exception at views.py at line 621
3. later when I want to add the same name again it says the category already exists there and indeed its added to category. I think it's a bug.
4. Add a category modal : I think instead of "summary" nice to have "add new category"

**Comment by sanjuktasen** [comment]
1.After adding the category user should be able to delete and edit the added category delete option just like they can do on home name. 
2.when I want to add summary name at first it breaks and says exception at views.py at line 621
3.later when I want to add the same name again it says the category already exists there and indeed its added to category. I think it's a bug.
4.Add a category modal : I think instead of "summary" nice to have "add new category"

**Pull request merged**
