### PR TITLE
Invite with names

### PR DESCRIPTION
**Pull request by cdschmitz**
Includes first and last name in the form for sending out email invitations.  This is used to personalize the email with the first name, and pre-populates the first and last name fields when the homebuyer clicks on the registration link.  Messaging is currently broken but will be fixed after merging in the success-messages branch.

### CODE REVIEW

**Comment by sjshoemak** [comment]
Fields relating the HB1 vs HB2 should be indicated

**Comment by sjshoemak** [comment]
1) Failed attemps to invite (due to reuse of email) fails silently.
2) Should fields remain populated after closing modal? Ties into first problem of silently failing as well as partially filled forms being closed with "x" in the top right corner.

**Comment by colepalm** [comment]
The "email invite sent" message only displays after logging out. Probably intentional, but it seems like it might be a little more practical upon re-visit to the homepage.

**Comment by colepalm** [comment]
Looks and functions well otherwise.

+1

**Pull request closed without merging**
